# Site settings
title: Jess Hamilton  
email: jesshami@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The work of a curious design student exploring landscape, data and cities
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jesshami  
github_username:  jesshami

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"